# Generated by Django 5.0.4 on 2024-05-07 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='note',
            table='notetaking',
        ),
    ]
